apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: tp
  name: part2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: part2
  template:
    metadata:
      labels:
        app: part2
    spec:
      containers:
      - name: api
        image: registry.cluster.wik.cloud/public/echo
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mon-service
  namespace: tp
spec:
  selector:
    app: part2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tpkubernetes-ingress
  namespace: tp
spec:
  ingressClassName: nginx
  rules:
  - host: tpkubernetes.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: mon-service
            port:
              number: 8080
